name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  infra-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      ARTGALLERYCSV: "https://data.cityofnewyork.us/api/views/43hw-uvdj/rows.csv?date=20241016&accessType=DOWNLOAD"
      ELASTIC_SEARCH_INDEX: "nyc-art-galleries"
      ELASTIC_VECTOR_FIELD: "embedding"
      ELASTIC_EMBEDDING_MODEL_ID: "azure_openai_embeddings"
      ELASTIC_COMPLETION_MODEL_ID: "azure_openai_completions"
      ELASTIC_INFERENCE_PIPELINE_MODEL_ID: "inferences_pipeline"
      AZURE_EMBEDDING_API_VERSION: "2023-05-15"
      AZURE_COMPLETION_API_VERSION: "2024-08-01-preview"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: 'Az CLI login'
      uses: Azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: 'Setup Node.js'
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 18
        
    - name: 'AZD: Install'
      uses: Azure/setup-azd@v1.0.0
      
    - name: 'AZD: Auth'
      run: azd config set auth.useAzCliAuth "true"

    - name: Provision Infrastructure
      id: deploy_bicep
      run: |
        azd provision --no-state --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ELASTIC_SEARCH_INDEX: ${{ vars.ELASTIC_SEARCH_INDEX }}
        ELASTIC_VECTOR_FIELD: ${{ vars.ELASTIC_VECTOR_FIELD }}
        ELASTIC_EMBEDDING_MODEL_ID: ${{ vars.ELASTIC_EMBEDDING_MODEL_ID }}
        ELASTIC_COMPLETION_MODEL_ID: ${{ vars.ELASTIC_COMPLETION_MODEL_ID }}
        ELASTIC_INFERENCE_PIPELINE_MODEL_ID: ${{ vars.ELASTIC_INFERENCE_PIPELINE_MODEL_ID }}
        AZURE_EMBEDDING_API_VERSION: ${{ vars.AZURE_EMBEDDING_API_VERSION }}
        # AZURE_COMPLETION_API_VERSION: ${{ vars.AZURE_COMPLETION_API_VERSION }}

    - name: 'NPM: Build'
      run: |
        rm -rf node_modules
        rm -rf package-lock.json
        npm install react-scripts
        
    - name: Deploy Application
      run: azd deploy --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
