name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  infra-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: 'Az CLI login'
      uses: Azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: 'Setup Node.js'
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 18
        
    - name: 'AZD: Install'
      uses: Azure/setup-azd@v1.0.0
      
    - name: 'AZD: Auth'
      run: azd config set auth.useAzCliAuth "true"

    - name: Provision Infrastructure
      id: deploy_bicep
      run: azd provision --no-state --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: "echo"
      run: echo ${{ steps.deploy_bicep.outputs.staticWebAppName }}
      
    - name: 'NPM: Build'
      run: |
        rm -rf node_modules
        rm -rf package-lock.json
        npm install react-scripts
        
    - name: Deploy Application
      run: azd deploy --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        STATIC_WEB_APP_NAME: ${{ steps.deploy_bicep.outputs.staticWebAppName }}"
